devCluster:
  enabled: false

corednsKubeSystem:
  enabled: false

hubClusterSecret:
  enabled: false

argo-cd:
  fullnameOverride: argocd

  redisSecretInit:
    enabled: true

  server:
    httproute:
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/class: cloudflare
      hostnames:
        - argocd.wion.trade
