apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ .Values.clusterName | quote }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    app.kubernetes.io/name: wion-trade-cluster
    app.kubernetes.io/component: cluster
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.244.0.0/16
    services:
      cidrBlocks:
        - 10.96.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: TalosControlPlane
    name: {{ printf "%s-control-plane" .Values.clusterName | quote }}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    kind: ProxmoxCluster
    name: {{ .Values.clusterName | quote }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: ProxmoxCluster
metadata:
  name: {{ .Values.clusterName | quote }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    app.kubernetes.io/name: wion-trade-cluster
    app.kubernetes.io/component: cluster
spec:
  controlPlaneEndpoint:
    host: {{ .Values.controlPlaneEndpoint.host | quote }}
    port: {{ .Values.controlPlaneEndpoint.port }}
  credentialsRef:
    name: {{ .Values.credentialsRef.secretName | quote }}
  dnsServers:
    {{- toYaml .Values.network.dnsServers | nindent 4 }}
  ipv4Config:
    addresses:
      {{- toYaml .Values.network.ipv4Addresses | nindent 6 }}
    gateway: {{ .Values.network.gateway | quote }}
    prefix: {{ .Values.network.prefix }}
