{{- range .Values.gateway.publicCertificates }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .secretName }}
  namespace: {{ $.Values.gateway.namespace }}
  labels:
    app.kubernetes.io/name: cilium-gateway
    app.kubernetes.io/component: gateway
spec:
  secretName: {{ .secretName }}
  issuerRef:
    name: {{ .clusterIssuerName }}
    kind: ClusterIssuer
  dnsNames:
    {{- toYaml .dnsNames | nindent 4 }}
{{- end }}
