{{- if .Values.redisSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: argocd-redis
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  labels:
    app.kubernetes.io/name: argocd-redis
    app.kubernetes.io/part-of: argocd
type: Opaque
data:
  auth: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
