apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.providers.core.namespace | quote }}
  labels:
    app.kubernetes.io/name: cluster-api
    app.kubernetes.io/component: core-provider
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: CoreProvider
metadata:
  name: {{ .Values.providers.core.name | quote }}
  namespace: {{ .Values.providers.core.namespace | quote }}
  labels:
    app.kubernetes.io/name: cluster-api
    app.kubernetes.io/component: core-provider
spec:
  version: {{ .Values.providers.core.version | quote }}
